fix(halyard): Use Halyard's spinnaker.yml defined Redis (#874)
Otherwise Rosco tries and fails to connect to code fallback of
redis://localhost:6379

Tested in Halyard with a custom BOM and halconfigs.

```
2022-04-26 00:32:12.895 ERROR 1 --- [RxIoScheduler-2] c.n.spinnaker.rosco.executor.BakePoller  : Update Polling Error:

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool

<snip>
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
```

(cherry picked from commit 64fa42ad55b7d5ec5cd8392aa3782a52fb7f7cc6)